name: Release Security

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run DigiCert Code Scan composite action
        uses: ./.github/actions/digicert-code-scan
        with:
          region: cluster-local
          api-key: ${{ secrets.DIGICERT_BACKEND_API_KEY }}
          with-release: false
          name: prod-release
          tag: v1.0.0.1
